### PR TITLE
!gbr, clean-up, tested

### PR DESCRIPTION
**Pull request by jordan-git**

### CODE REVIEW

**Comment by jordan-git** [comment]
Don't forget the Discord.inc timestamp changes

**Comment by jordan-git** [comment]
Discord.inc modified by @TGoldenB

**Comment by deejcoder** [comment]
Pending comment from @TGoldenB to determine if he has completed the changes in PAWN.

**Comment by jordan-git** [comment]
@dy1zan http://gitlab.com/sarpdev/DevelopmentTeam/commit/d0b97b1a5af789b63d2d57f28a87302a296190bf
Although I cannot view it.

**Pull request merged**
